In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [7]:
x=pd.read_csv(r"C:\NB\Movie Recommendation System\machine-learning-online-2018\5. K-Nearest Neighbours\train.csv")

In [8]:
x.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [9]:
data=x.values

In [10]:
print(data)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [16]:
x=data[:,1:]
y=data[:,0]

In [17]:
print(x.shape)
print(y.shape)

(42000, 784)
(42000,)


In [32]:
def draw(ex):
    ex=ex.reshape((28,28))
    plt.imshow(ex)
    plt.show()
    

In [24]:
split=int(0.7*x.shape[0])
x_train=data[:split,1:]
y_train=data[:split,0]
x_test=data[split:,1:]
y_test=data[split:,0]

In [35]:
def dist(x2,x1):
    return np.sqrt(sum((x2-x1)**2))
def knn(x,y,query,k=5):
    vals=[]
    n=x.shape[0]
    for i in range(n):
        d=dist(x[i],query)
        vals.append((d,y[i]))
    vals=sorted(vals)
    vals=vals[:k]
    vals=np.array(vals)
    val=np.unique(vals[:,1],return_counts=True)
    index=val[1].argmax()
    pred=val[0][index]
    return pred

In [38]:
pred=knn(x_train,y_train,x_test[123])
print(int(pred))
draw(x_test[123])

6
